### ISSUE TITLE
[AOS/feat] 안드로이드 스튜디오 프로젝트 생성

### ISSUE THREAD

**Issue by ajang369** [JNU-econovation/Gaebaljip#12]
## 🚨 Issue

- 안드로이드 스튜디오 프로젝트 생성 및 환경 세팅

## ✅ To Do List

- [x] 브랜치 생성
- [x] 프로젝트 생성
- [x] 환경 세팅

**Comment by rootachieve** [comment]
폴더 외부에 프로젝트를 생성해서 다시 이슈 오픈합니다.
