### ISSUE TITLE
[AOS/bug] 바텀 네비게이션 적용

### ISSUE THREAD

**Issue by ajang369** [JNU-econovation/Gaebaljip#49]
> **브랜치 base 생성 오류로 인해 close 한 후 다시 이슈 생성합니다.**

## ⚠️ Issue
- Bottom Navigation Bar로 각 화면을 전환할 수 있습니다.

## ✏️ To Do List
- [ ] 홈, 캘린더, 등록, 추천, 알람 화면 파일 만들기
- [ ] 바텀 네비게이션 아이템 만들기
- [ ] MainActivity에 적용

## ETC
수정할 사항
- 메인 컬러에 맞게 background와 content 색깔 변경
- material design3 학습 후 적용
- 네비게이션 기능 학습 후 수정

---

**Comment by rootachieve** [comment]
close 사유를 추가했습니다.
